# docker compose -f mongo-stack.yml up --force-recreate -d 

version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - global-default
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-coog}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-coog}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE:-coog-services}"
    volumes:
      - ${MONGODB_DATA_VOLUME:?}:/data/db
      

  mongo_express:
    image: mongo-express:latest
    container_name: mongodb_express
    networks:
      - global-default
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME:-coog}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-coog}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME:-coog}:${MONGO_INITDB_ROOT_USERNAME:-coog}@mongo:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN:-coog}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD:-coog}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: "admin"
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
    depends_on:
      - mongo
    volumes:
      - ${MONGODB_DATA_VOLUME:?}:/data/mongo_express

networks:
  global-default:
    external: true